name: Analize Commit

on:
  push:
    branches: [ main ]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wagoid/commitlint-github-action@v2
